# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

port: 4002

title: Toms.click

author:
  name: Martin Toms
  thumbnail: "/assets/martin.svg"
  sameAs: "https://github.com/morgosus"
  givenName: Martin
  familyName: Toms
  gender: male
  alternateName: morgosus
  url: https://martin.toms.click
  email: martin@toms.click
  alumniOf:
    type: CollegeOrUniversity
    name: Czech University of Life Sciences Prague
    url: https://en.wikipedia.org/wiki/Czech_University_of_Life_Sciences_Prague
    startDate: 1906

email: contact@toms.click
description: >- # this means to ignore newlines until "baseurl:"
  Great content and awesome gaming tips await you (you wouldn’t want to miss that). I always do my best to make sure the writeups here are as informative as they can, to make your visit worthwhile. You’ll find useful blog posts about programming and Fallout Shelter Online, but soon I’ll also be writing about other games.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: morgosus
instagram_username: morgosus
youtube_username: MartinToms-CzechRepublic
stackoverflow_username: morgosus

comments: true

github_comments_repository: morgosus/morgosus.github.io

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-redirect-from

# Own
show_excerpts: true
excerpt_length: 240
permalink: /:categories/:title

sass:
  load_paths:
    - _sass
    - node_modules
    - assets/css
    - assets/vendor
  style: compressed

collections:
  thumbnail:
  author:
  featured:

feed:
  categories:
    - programming
    - gaming